name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'  # 👈 Make sure this matches your pubspec.yaml requirements
          channel: 'stable'

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get
        working-directory: theme_custom

      # Analyze project
      - name: Analyze code
        run: flutter analyze
        working-directory: theme_custom

      # Run tests
      - name: Run tests
        run: flutter test
        working-directory: theme_custom

      # Build APK
      - name: Build release APK
        run: flutter build apk --release
        working-directory: theme_custom

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-apk
          path: theme_custom/build/app/outputs/flutter-apk/app-release.apk
